export const batchAuctionHouseAbi = [
  {
    type: 'function',
    name: 'bid',
    inputs: [
      { name: '_originContract', type: 'address', internalType: 'address' },
      { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
      { name: '_currencyAddress', type: 'address', internalType: 'address' },
      { name: '_amount', type: 'uint128', internalType: 'uint128' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'bidWithAuctionMerkleProof',
    inputs: [
      { name: '_currencyAddress', type: 'address', internalType: 'address' },
      { name: '_originContract', type: 'address', internalType: 'address' },
      { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
      { name: '_creator', type: 'address', internalType: 'address' },
      { name: '_merkleRoot', type: 'bytes32', internalType: 'bytes32' },
      { name: '_bidAmount', type: 'uint128', internalType: 'uint128' },
      { name: '_proof', type: 'bytes32[]', internalType: 'bytes32[]' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'cancelAuctionMerkleRoot',
    inputs: [{ name: '_root', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getAuctionDetails',
    inputs: [
      { name: '_originContract', type: 'address', internalType: 'address' },
      { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint32', internalType: 'uint32' },
      { name: '', type: 'uint64', internalType: 'uint64' },
      { name: '', type: 'uint64', internalType: 'uint64' },
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint128', internalType: 'uint128' },
      { name: '', type: 'address[]', internalType: 'address payable[]' },
      { name: '', type: 'uint8[]', internalType: 'uint8[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getCreatorAuctionMerkleRootNonce',
    inputs: [
      { name: '_user', type: 'address', internalType: 'address' },
      { name: '_root', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [{ name: '', type: 'uint32', internalType: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getCurrentBid',
    inputs: [
      { name: '_originContract', type: 'address', internalType: 'address' },
      { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: 'bidder', type: 'address', internalType: 'address' },
      { name: 'currencyAddress', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint128', internalType: 'uint128' },
      { name: 'marketplaceFeeAtTime', type: 'uint8', internalType: 'uint8' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getMerkleAuctionConfig',
    inputs: [
      { name: '_creator', type: 'address', internalType: 'address' },
      { name: '_root', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct IRareBatchAuctionHouse.MerkleAuctionConfig',
        components: [
          { name: 'currency', type: 'address', internalType: 'address' },
          { name: 'startingAmount', type: 'uint128', internalType: 'uint128' },
          { name: 'duration', type: 'uint64', internalType: 'uint64' },
          { name: 'nonce', type: 'uint32', internalType: 'uint32' },
          { name: 'splitAddresses', type: 'address[]', internalType: 'address payable[]' },
          { name: 'splitRatios', type: 'uint8[]', internalType: 'uint8[]' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTokenAuctionNonce',
    inputs: [
      { name: '_creator', type: 'address', internalType: 'address' },
      { name: '_root', type: 'bytes32', internalType: 'bytes32' },
      { name: '_tokenContract', type: 'address', internalType: 'address' },
      { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'uint32', internalType: 'uint32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUserAuctionMerkleRoots',
    inputs: [{ name: '_user', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'bytes32[]', internalType: 'bytes32[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isTokenInRoot',
    inputs: [
      { name: '_root', type: 'bytes32', internalType: 'bytes32' },
      { name: '_origin', type: 'address', internalType: 'address' },
      { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
      { name: '_proof', type: 'bytes32[]', internalType: 'bytes32[]' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'registerAuctionMerkleRoot',
    inputs: [
      { name: '_merkleRoot', type: 'bytes32', internalType: 'bytes32' },
      { name: '_currency', type: 'address', internalType: 'address' },
      { name: '_startingAmount', type: 'uint128', internalType: 'uint128' },
      { name: '_duration', type: 'uint64', internalType: 'uint64' },
      { name: '_splitAddresses', type: 'address[]', internalType: 'address payable[]' },
      { name: '_splitRatios', type: 'uint8[]', internalType: 'uint8[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'settleAuction',
    inputs: [
      { name: '_originContract', type: 'address', internalType: 'address' },
      { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'AuctionBid',
    inputs: [
      { name: 'contractAddress', type: 'address', indexed: true, internalType: 'address' },
      { name: 'bidder', type: 'address', indexed: true, internalType: 'address' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'currencyAddress', type: 'address', indexed: false, internalType: 'address' },
      { name: 'amount', type: 'uint128', indexed: false, internalType: 'uint128' },
      { name: 'marketplaceFee', type: 'uint8', indexed: false, internalType: 'uint8' },
      { name: 'previousBidder', type: 'address', indexed: false, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'AuctionMerkleBid',
    inputs: [
      { name: 'contractAddress', type: 'address', indexed: true, internalType: 'address' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'bidder', type: 'address', indexed: true, internalType: 'address' },
      { name: 'creator', type: 'address', indexed: false, internalType: 'address' },
      { name: 'currencyAddress', type: 'address', indexed: false, internalType: 'address' },
      { name: 'merkleRoot', type: 'bytes32', indexed: false, internalType: 'bytes32' },
      { name: 'amount', type: 'uint128', indexed: false, internalType: 'uint128' },
      { name: 'nonce', type: 'uint32', indexed: false, internalType: 'uint32' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'AuctionMerkleRootCancelled',
    inputs: [
      { name: 'creator', type: 'address', indexed: true, internalType: 'address' },
      { name: 'merkleRoot', type: 'bytes32', indexed: true, internalType: 'bytes32' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'AuctionMerkleRootRegistered',
    inputs: [
      { name: 'creator', type: 'address', indexed: true, internalType: 'address' },
      { name: 'merkleRoot', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'currencyAddress', type: 'address', indexed: false, internalType: 'address' },
      { name: 'startingAmount', type: 'uint128', indexed: false, internalType: 'uint128' },
      { name: 'duration', type: 'uint64', indexed: false, internalType: 'uint64' },
      { name: 'nonce', type: 'uint32', indexed: false, internalType: 'uint32' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'AuctionSettled',
    inputs: [
      { name: 'contractAddress', type: 'address', indexed: true, internalType: 'address' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'seller', type: 'address', indexed: false, internalType: 'address' },
      { name: 'bidder', type: 'address', indexed: false, internalType: 'address' },
      { name: 'amount', type: 'uint128', indexed: false, internalType: 'uint128' },
      { name: 'currencyAddress', type: 'address', indexed: false, internalType: 'address' },
      { name: 'marketplaceFee', type: 'uint8', indexed: false, internalType: 'uint8' },
    ],
    anonymous: false,
  },
] as const;
