export const liquidFactoryAbi = [
  {
    type: 'error',
    name: 'EnforcedPause',
    inputs: [],
  },
  {
    type: 'error',
    name: 'ImplementationNotSet',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidAmount',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidName',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidPoolHook',
    inputs: [{ name: 'poolHooks', type: 'address' }],
  },
  {
    type: 'error',
    name: 'InvalidSymbol',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidTickRange',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidTickSpacing',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidTokenURI',
    inputs: [],
  },
  {
    type: 'error',
    name: 'PoolHookMissingFlags',
    inputs: [
      { name: 'poolHooks', type: 'address' },
      { name: 'actualFlags', type: 'uint160' },
      { name: 'requiredFlags', type: 'uint160' },
    ],
  },
  {
    type: 'error',
    name: 'PoolHookNotGuard',
    inputs: [{ name: 'poolHooks', type: 'address' }],
  },
  {
    type: 'error',
    name: 'PoolHooksNotSet',
    inputs: [],
  },
  {
    type: 'error',
    name: 'SafeERC20FailedOperation',
    inputs: [{ name: 'token', type: 'address' }],
  },
  {
    type: 'error',
    name: 'SwapGuardFactoryMismatch',
    inputs: [
      { name: 'poolHooks', type: 'address' },
      { name: 'configuredFactory', type: 'address' },
      { name: 'expectedFactory', type: 'address' },
    ],
  },
  {
    type: 'error',
    name: 'Unauthorized',
    inputs: [],
  },
  {
    type: 'function',
    name: 'baseToken',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxTotalSupply',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'creatorLaunchReward',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'minRareLiquidityWei',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lpTickLower',
    inputs: [],
    outputs: [{ name: '', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lpTickUpper',
    inputs: [],
    outputs: [{ name: '', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'poolTickSpacing',
    inputs: [],
    outputs: [{ name: '', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'poolHooks',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'createLiquidTokenMultiCurve',
    inputs: [
      { name: '_creator', type: 'address' },
      { name: '_tokenUri', type: 'string' },
      { name: '_name', type: 'string' },
      { name: '_symbol', type: 'string' },
      { name: '_initialRareLiquidity', type: 'uint256' },
      {
        name: '_curves',
        type: 'tuple[]',
        components: [
          { name: 'tickLower', type: 'int24' },
          { name: 'tickUpper', type: 'int24' },
          { name: 'numPositions', type: 'uint16' },
          { name: 'shares', type: 'uint256' },
        ],
      },
    ],
    outputs: [{ name: 'token', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createLiquidTokenMultiCurveWithSupply',
    inputs: [
      { name: '_creator', type: 'address' },
      { name: '_tokenUri', type: 'string' },
      { name: '_name', type: 'string' },
      { name: '_symbol', type: 'string' },
      { name: '_initialRareLiquidity', type: 'uint256' },
      {
        name: '_curves',
        type: 'tuple[]',
        components: [
          { name: 'tickLower', type: 'int24' },
          { name: 'tickUpper', type: 'int24' },
          { name: 'numPositions', type: 'uint16' },
          { name: 'shares', type: 'uint256' },
        ],
      },
      { name: '_customMaxTotalSupply', type: 'uint256' },
    ],
    outputs: [{ name: 'token', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'LiquidTokenCreated',
    inputs: [
      { name: 'token', type: 'address', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'tokenUri', type: 'string', indexed: false },
    ],
    anonymous: false,
  },
] as const;
