export const rareErc1155MarketplaceAbi = [
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'contractAddress', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'seller', type: 'address' },
      { indexed: false, internalType: 'address', name: 'currency', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'price', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'startTime', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'maxMints', type: 'uint256' },
      { indexed: false, internalType: 'address[]', name: 'splitRecipients', type: 'address[]' },
      { indexed: false, internalType: 'uint8[]', name: 'splitRatios', type: 'uint8[]' },
    ],
    name: 'PrepareMintDirectSale',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'contractAddress', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'payer', type: 'address' },
      { indexed: true, internalType: 'address', name: 'recipient', type: 'address' },
      { indexed: false, internalType: 'address', name: 'seller', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'quantity', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'currency', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'price', type: 'uint256' },
    ],
    name: 'MintDirectSale',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'contractAddress', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'MintDirectSaleCancelled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'itemIndex', type: 'uint256' },
      { indexed: false, internalType: 'uint8', name: 'itemKind', type: 'uint8' },
      { indexed: true, internalType: 'address', name: 'contractAddress', type: 'address' },
      { indexed: true, internalType: 'address', name: 'payer', type: 'address' },
      { indexed: true, internalType: 'address', name: 'recipient', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'seller', type: 'address' },
      { indexed: false, internalType: 'address', name: 'currencyAddress', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'price', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'quantity', type: 'uint256' },
      { indexed: false, internalType: 'bool', name: 'filled', type: 'bool' },
      { indexed: false, internalType: 'enum IRareERC1155MarketplaceTypes.CheckoutFailureStage', name: 'failureStage', type: 'uint8' },
      { indexed: false, internalType: 'bytes4', name: 'reason', type: 'bytes4' },
      { indexed: false, internalType: 'bytes', name: 'failureData', type: 'bytes' },
      { indexed: false, internalType: 'uint256', name: 'totalPaid', type: 'uint256' },
    ],
    name: 'CheckoutItemProcessed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'payer', type: 'address' },
      { indexed: true, internalType: 'address', name: 'recipient', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'filledCount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'skippedCount', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'ethSpent', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'ethRefunded', type: 'uint256' },
    ],
    name: 'CheckoutCompleted',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'address', name: '_currencyAddress', type: 'address' },
      {
        components: [
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'price', type: 'uint256' },
          { internalType: 'uint256', name: 'startTime', type: 'uint256' },
          { internalType: 'uint256', name: 'maxMints', type: 'uint256' },
        ],
        internalType: 'struct IRareERC1155MarketplaceTypes.DirectSaleRequest[]',
        name: '_requests',
        type: 'tuple[]',
      },
      { internalType: 'address[]', name: '_splitRecipients', type: 'address[]' },
      { internalType: 'uint8[]', name: '_splitRatios', type: 'uint8[]' },
    ],
    name: 'prepareMintDirectSales',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'uint256[]', name: '_tokenIds', type: 'uint256[]' },
    ],
    name: 'cancelMintDirectSales',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      {
        components: [
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'bytes32', name: 'root', type: 'bytes32' },
          { internalType: 'uint256', name: 'endTimestamp', type: 'uint256' },
        ],
        internalType: 'struct IRareERC1155MarketplaceTypes.AllowListConfigRequest[]',
        name: '_requests',
        type: 'tuple[]',
      },
    ],
    name: 'setTokenAllowListConfigs',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      {
        components: [
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'limit', type: 'uint256' },
        ],
        internalType: 'struct IRareERC1155MarketplaceTypes.TokenLimitRequest[]',
        name: '_requests',
        type: 'tuple[]',
      },
    ],
    name: 'setTokenMintLimits',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      {
        components: [
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'limit', type: 'uint256' },
        ],
        internalType: 'struct IRareERC1155MarketplaceTypes.TokenLimitRequest[]',
        name: '_requests',
        type: 'tuple[]',
      },
    ],
    name: 'setTokenTxLimits',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'address', name: '_currencyAddress', type: 'address' },
      {
        components: [
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'price', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
          { internalType: 'uint256', name: 'expirationTime', type: 'uint256' },
        ],
        internalType: 'struct IRareERC1155MarketplaceTypes.SalePriceRequest[]',
        name: '_requests',
        type: 'tuple[]',
      },
      { internalType: 'address[]', name: '_splitRecipients', type: 'address[]' },
      { internalType: 'uint8[]', name: '_splitRatios', type: 'uint8[]' },
    ],
    name: 'setSalePrices',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'uint256[]', name: '_tokenIds', type: 'uint256[]' },
    ],
    name: 'cancelSalePrices',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'address', name: '_currencyAddress', type: 'address' },
      { internalType: 'uint256', name: '_price', type: 'uint256' },
      { internalType: 'uint256', name: '_quantity', type: 'uint256' },
      { internalType: 'uint256', name: '_expirationTime', type: 'uint256' },
    ],
    name: 'makeOffer',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'seller', type: 'address' },
      { indexed: true, internalType: 'address', name: 'payer', type: 'address' },
      { indexed: true, internalType: 'address', name: 'contractAddress', type: 'address' },
      { indexed: true, internalType: 'address', name: 'recipient', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: false, internalType: 'address', name: 'currency', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'price', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'quantity', type: 'uint256' },
    ],
    name: 'Sold',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'address', name: '_recipient', type: 'address' },
      {
        components: [
          { internalType: 'uint8', name: 'itemKind', type: 'uint8' },
          { internalType: 'address', name: 'contractAddress', type: 'address' },
          { internalType: 'address', name: 'seller', type: 'address' },
          { internalType: 'address', name: 'currencyAddress', type: 'address' },
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'price', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
          { internalType: 'bytes32[]', name: 'proof', type: 'bytes32[]' },
        ],
        internalType: 'struct IRareERC1155MarketplaceTypes.CheckoutItem[]',
        name: '_items',
        type: 'tuple[]',
      },
    ],
    name: 'checkout',
    outputs: [
      {
        components: [
          {
            components: [
              { internalType: 'uint256', name: 'filledCount', type: 'uint256' },
              { internalType: 'uint256', name: 'skippedCount', type: 'uint256' },
              { internalType: 'uint256', name: 'ethSpent', type: 'uint256' },
              { internalType: 'uint256', name: 'ethRefunded', type: 'uint256' },
            ],
            internalType: 'struct IRareERC1155MarketplaceTypes.CheckoutSummary',
            name: 'summary',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'uint256', name: 'itemIndex', type: 'uint256' },
              { internalType: 'uint8', name: 'itemKind', type: 'uint8' },
              { internalType: 'address', name: 'contractAddress', type: 'address' },
              { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
              { internalType: 'address', name: 'seller', type: 'address' },
              { internalType: 'address', name: 'currencyAddress', type: 'address' },
              { internalType: 'uint256', name: 'price', type: 'uint256' },
              { internalType: 'uint256', name: 'quantity', type: 'uint256' },
              { internalType: 'bool', name: 'filled', type: 'bool' },
              { internalType: 'enum IRareERC1155MarketplaceTypes.CheckoutFailureStage', name: 'failureStage', type: 'uint8' },
              { internalType: 'bytes4', name: 'reason', type: 'bytes4' },
              { internalType: 'bytes', name: 'failureData', type: 'bytes' },
              { internalType: 'uint256', name: 'totalPaid', type: 'uint256' },
            ],
            internalType: 'struct IRareERC1155MarketplaceTypes.CheckoutItemResult[]',
            name: 'items',
            type: 'tuple[]',
          },
        ],
        internalType: 'struct IRareERC1155MarketplaceTypes.CheckoutExecution',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'address', name: '_currencyAddress', type: 'address' },
    ],
    name: 'cancelOffer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'address', name: '_currencyAddress', type: 'address' },
      { internalType: 'address', name: '_recipient', type: 'address' },
      {
        components: [
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'price', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
          { internalType: 'bytes32[]', name: 'proof', type: 'bytes32[]' },
        ],
        internalType: 'struct IRareERC1155MarketplaceTypes.MintRequest[]',
        name: '_requests',
        type: 'tuple[]',
      },
    ],
    name: 'mintDirectSaleBatch',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'address', name: '_seller', type: 'address' },
      { internalType: 'address', name: '_currencyAddress', type: 'address' },
      { internalType: 'address', name: '_recipient', type: 'address' },
      {
        components: [
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'price', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
        ],
        internalType: 'struct IRareERC1155MarketplaceTypes.BuyRequest[]',
        name: '_requests',
        type: 'tuple[]',
      },
    ],
    name: 'buyBatch',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'address', name: '_buyer', type: 'address' },
      { internalType: 'address', name: '_currencyAddress', type: 'address' },
      { internalType: 'uint256', name: '_price', type: 'uint256' },
      { internalType: 'uint256', name: '_quantity', type: 'uint256' },
      { internalType: 'address[]', name: '_splitRecipients', type: 'address[]' },
      { internalType: 'uint8[]', name: '_splitRatios', type: 'uint8[]' },
    ],
    name: 'acceptOffer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
    ],
    name: 'getDirectSaleConfig',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'seller', type: 'address' },
          { internalType: 'address', name: 'currencyAddress', type: 'address' },
          { internalType: 'uint256', name: 'price', type: 'uint256' },
          { internalType: 'uint256', name: 'startTime', type: 'uint256' },
          { internalType: 'uint256', name: 'maxMints', type: 'uint256' },
          { internalType: 'address[]', name: 'splitRecipients', type: 'address[]' },
          { internalType: 'uint8[]', name: 'splitRatios', type: 'uint8[]' },
        ],
        internalType: 'struct IRareERC1155MarketplaceTypes.DirectSaleConfig',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
    ],
    name: 'getTokenAllowListConfig',
    outputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'root', type: 'bytes32' },
          { internalType: 'uint256', name: 'endTimestamp', type: 'uint256' },
        ],
        internalType: 'struct IRareERC1155MarketplaceTypes.AllowListConfig',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
    ],
    name: 'getTokenMintLimit',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'address', name: '_account', type: 'address' },
    ],
    name: 'getTokenMintsPerAddress',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
    ],
    name: 'getTokenTxLimit',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'address', name: '_account', type: 'address' },
    ],
    name: 'getTokenTxsPerAddress',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'address', name: '_seller', type: 'address' },
    ],
    name: 'getSalePrice',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'currencyAddress', type: 'address' },
          { internalType: 'uint256', name: 'price', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
          { internalType: 'uint256', name: 'expirationTime', type: 'uint256' },
          { internalType: 'address[]', name: 'splitRecipients', type: 'address[]' },
          { internalType: 'uint8[]', name: 'splitRatios', type: 'uint8[]' },
        ],
        internalType: 'struct IRareERC1155MarketplaceTypes.SalePrice',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_contractAddress', type: 'address' },
      { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
      { internalType: 'address', name: '_buyer', type: 'address' },
      { internalType: 'address', name: '_currencyAddress', type: 'address' },
    ],
    name: 'getOffer',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'currencyAddress', type: 'address' },
          { internalType: 'uint256', name: 'price', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
          { internalType: 'uint256', name: 'marketplaceFeeRemaining', type: 'uint256' },
          { internalType: 'uint256', name: 'expirationTime', type: 'uint256' },
        ],
        internalType: 'struct IRareERC1155MarketplaceTypes.Offer',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getERC1155ApprovalManager',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'isPaused',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'required', type: 'uint256' },
      { internalType: 'uint256', name: 'provided', type: 'uint256' },
    ],
    name: 'InsufficientCheckoutETH',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'address', name: 'currencyAddress', type: 'address' },
      { internalType: 'uint256', name: 'required', type: 'uint256' },
      { internalType: 'uint256', name: 'available', type: 'uint256' },
    ],
    name: 'InsufficientCheckoutERC20Balance',
    type: 'error',
  },
  {
    inputs: [
      { internalType: 'address', name: 'currencyAddress', type: 'address' },
      { internalType: 'uint256', name: 'required', type: 'uint256' },
      { internalType: 'uint256', name: 'allowance', type: 'uint256' },
    ],
    name: 'InsufficientCheckoutERC20Allowance',
    type: 'error',
  },
  {
    inputs: [{ internalType: 'uint8', name: 'itemKind', type: 'uint8' }],
    name: 'UnsupportedCheckoutItemKind',
    type: 'error',
  },
  {
    inputs: [],
    name: 'RecipientCannotBeZero',
    type: 'error',
  },
] as const;
