/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/nfts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List NFTs
         * @description Search, filter, and list NFTs with rich query parameters
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    perPage?: number;
                    /** @description Full-text search */
                    q?: string;
                    /** @description Checksummed Ethereum address */
                    creatorAddress?: components["schemas"]["EthereumAddress"];
                    /** @description Checksummed Ethereum address */
                    ownerAddress?: components["schemas"]["EthereumAddress"];
                    /** @description Checksummed Ethereum address */
                    contractAddress?: components["schemas"]["EthereumAddress"] & unknown;
                    collectionId?: string;
                    /** @description Supported blockchain network id */
                    chainId?: components["schemas"]["ChainId"];
                    listingType?: "SALE_PRICE" | "BATCH_SALE_PRICE";
                    hasAuction?: boolean | null;
                    auctionState?: "PENDING" | "RUNNING" | "UNSETTLED";
                    auctionType?: "RESERVE_AUCTION" | "BATCH_RESERVE_AUCTION" | "SCHEDULED_AUCTION";
                    /** @description Checksummed Ethereum address */
                    auctionCreatorAddress?: components["schemas"]["EthereumAddress"];
                    /** @description Checksummed Ethereum address */
                    auctionBidderAddress?: components["schemas"]["EthereumAddress"];
                    hasListing?: boolean | null;
                    hasOffer?: boolean | null;
                    /** @description Checksummed Ethereum address */
                    offerBuyerAddress?: components["schemas"]["EthereumAddress"];
                    isPrimarySale?: boolean | null;
                    isSecondarySale?: boolean | null;
                    priceMin?: number | null;
                    priceMax?: number | null;
                    /** @description Checksummed Ethereum address */
                    currency?: components["schemas"]["EthereumAddress"] & unknown;
                    mediaType?: "AUDIO" | "HTML" | "IMAGE" | "THREE_D" | "VIDEO";
                    tags?: string[] | string;
                    sortBy?: "newest" | "oldest" | "priceAsc" | "priceDesc" | "recentlySold" | "auctionEndingSoon" | "recentActivity" | "bidAsc" | "bidDesc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of NFTs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Nft"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/nfts/{universalTokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get NFT
         * @description Get a single NFT by its universal token ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Canonical NFT identifier in chainId-contractAddress-tokenId format. */
                    universalTokenId: components["schemas"]["UniversalTokenId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description NFT detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Nft"];
                        };
                    };
                };
                /** @description NFT not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/nfts/{universalTokenId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List NFT events
         * @description Get events for a specific NFT
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    perPage?: number;
                    eventType?: ("CANCEL_AUCTION" | "CANCEL_OFFER" | "CLOSE_AUCTION" | "CREATE_NFT" | "CREATE_NFT_SUPPLY" | "CREATE_RESERVE_AUCTION" | "CREATE_SCHEDULED_AUCTION" | "END_AUCTION" | "MAKE_AUCTION_BID" | "MAKE_LISTING" | "MAKE_OFFER" | "SETTLE_AUCTION" | "START_AUCTION" | "TAKE_LISTING" | "TAKE_OFFER" | "TRANSFER_NFT" | "TRANSFER_NFT_SUPPLY")[];
                    sortBy?: "newest" | "oldest";
                };
                header?: never;
                path: {
                    /** @description Canonical NFT identifier in chainId-contractAddress-tokenId format. */
                    universalTokenId: components["schemas"]["UniversalTokenId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of NFT events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["NftEvent"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/nfts/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pin NFT Metadata
         * @description Assemble NFT metadata JSON from media assets and pin to IPFS via Filebase
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateNftMetadataRequest"];
                };
            };
            responses: {
                /** @description Metadata pinned to IPFS */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateNftMetadataResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/nfts/metadata/media/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Media Upload
         * @description Initiate a multipart upload to Filebase/IPFS, returning presigned URLs for each part
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateMediaUploadRequest"];
                };
            };
            responses: {
                /** @description Multipart upload initiated */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateMediaUploadResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/nfts/metadata/media/uploads/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Media Upload
         * @description Complete a multipart upload, resolve IPFS CID, and return IPFS/gateway URLs
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteMediaUploadRequest"];
                };
            };
            responses: {
                /** @description Upload completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IpfsUploadResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/nfts/metadata/media/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Media Metadata
         * @description Call pipelines to extract media metadata (dimensions, size, type) from a URI
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GenerateMediaRequest"];
                };
            };
            responses: {
                /** @description Media metadata generated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenerateMediaResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List collections
         * @description Search, filter, and list collections
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    perPage?: number;
                    /** @description Full-text search */
                    q?: string;
                    /** @description Checksummed Ethereum address */
                    ownerAddress?: components["schemas"]["EthereumAddress"];
                    /** @description Supported blockchain network id */
                    chainId?: components["schemas"]["ChainId"];
                    sortBy?: "newest" | "oldest";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of collections */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Collection"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get collection
         * @description Get a single collection by ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Collection detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Collection"];
                        };
                    };
                };
                /** @description Collection not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List collection events
         * @description Get events across all NFTs in a collection
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    perPage?: number;
                    eventType?: ("CANCEL_AUCTION" | "CANCEL_OFFER" | "CLOSE_AUCTION" | "CREATE_NFT" | "CREATE_NFT_SUPPLY" | "CREATE_RESERVE_AUCTION" | "CREATE_SCHEDULED_AUCTION" | "END_AUCTION" | "MAKE_AUCTION_BID" | "MAKE_LISTING" | "MAKE_OFFER" | "SETTLE_AUCTION" | "START_AUCTION" | "TAKE_LISTING" | "TAKE_OFFER" | "TRANSFER_NFT" | "TRANSFER_NFT_SUPPLY")[];
                    sortBy?: "newest" | "oldest";
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of collection events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["NftEvent"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import ERC-721 Collection
         * @description Validate an ERC-721 contract on-chain and register it for indexing via pipelines
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImportCollectionRequest"];
                };
            };
            responses: {
                /** @description Collection imported or already exists */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportCollectionResponse"];
                    };
                };
                /** @description Validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Collection already indexed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            collectionId: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user
         * @description Get a user profile by Ethereum address
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Checksummed Ethereum address */
                    address: components["schemas"]["EthereumAddress"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["UserProfile"];
                        };
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tokens/price/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Token Price
         * @description Fetch the current USD price for a token by symbol (e.g., rare, eth, usdc)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Token symbol (case-insensitive) */
                    symbol: components["schemas"]["TokenSymbol"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token price */
                200: {
                    headers: {
                        "Cache-Control": string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPriceResponse"];
                    };
                };
                /** @description Token not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/merkle-roots/nfts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate NFT Merkle Root
         * @description Generate and store an NFT merkle root via the pipelines service
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GenerateNftMerkleRootRequest"];
                };
            };
            responses: {
                /** @description NFT merkle root generated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenerateNftMerkleRootResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Pipelines request failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/merkle-roots/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Address Merkle Root
         * @description Generate and store an address merkle root via the pipelines service
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GenerateAddressMerkleRootJsonRequest"];
                    "multipart/form-data": components["schemas"]["GenerateAddressMerkleRootFormRequest"];
                };
            };
            responses: {
                /** @description Address merkle root generated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenerateAddressMerkleRootResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Pipelines request failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/merkle-roots/nfts/proof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate NFT Merkle Proof
         * @description Resolve an NFT Merkle root and generate a token proof from the stored Merkle list
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GenerateNftMerkleProofRequest"];
                };
            };
            responses: {
                /** @description NFT Merkle proof generated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenerateNftMerkleProofResponse"];
                    };
                };
                /** @description Merkle root or NFT entry not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Multiple matching roots were found */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/merkle-roots/addresses/proof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Address Merkle Proof
         * @description Generate an address proof from a stored Merkle root list
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GenerateAddressMerkleProofRequest"];
                };
            };
            responses: {
                /** @description Address Merkle proof generated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenerateAddressMerkleProofResponse"];
                    };
                };
                /** @description Merkle root or address entry not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Multiple matching roots were found */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connect/intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Connect Intent
         * @description Create a hosted SuperRare Connect intent for auth, checkout, or supported actions.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateConnectIntentRequest"];
                };
            };
            responses: {
                /** @description Connect intent created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateConnectIntentResponse"];
                    };
                };
                /** @description Invalid connect intent request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect intent cannot be created */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connect/intents/{intentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Connect Intent
         * @description Get status for a SuperRare Connect intent.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Connect intent status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetConnectIntentResponse"];
                    };
                };
                /** @description Connect intent not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect intent expired */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connect/intents/{intentId}/execution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Hosted Connect Execution
         * @description Persist hosted execution status for a server-resolved SuperRare Connect action.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Intent-scoped execution token from the hosted Connect URL. */
                    "x-connect-execution-token"?: string;
                };
                path: {
                    intentId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateConnectIntentExecutionRequest"];
                };
            };
            responses: {
                /** @description Connect execution status updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateConnectIntentExecutionResponse"];
                    };
                };
                /** @description Connect execution token is missing or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect intent not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect intent execution cannot be updated */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect intent expired */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connect/intents/{intentId}/execution-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange Hosted Connect Execution Session
         * @description Exchange a short-lived hosted execution session for an intent-scoped execution token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intentId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExchangeConnectIntentExecutionSessionRequest"];
                };
            };
            responses: {
                /** @description Hosted execution token exchanged */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExchangeConnectIntentExecutionSessionResponse"];
                    };
                };
                /** @description Hosted execution session is missing, expired, or invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect intent not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect intent expired */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connect/auth/hosted-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Hosted Connect Auth
         * @description Issue a one-time Connect auth code after hosted SuperRare login succeeds.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteHostedConnectAuthRequest"];
                };
            };
            responses: {
                /** @description Hosted Connect auth completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompleteHostedConnectAuthResponse"];
                    };
                };
                /** @description Invalid hosted Connect auth completion request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Hosted login session is not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect intent not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect intent expired */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Hosted login auth service unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connect/auth/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange Connect Auth
         * @description Exchange a one-time hosted auth code for a SuperRare Connect session.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExchangeConnectAuthRequest"];
                };
            };
            responses: {
                /** @description Connect auth exchanged */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExchangeConnectAuthResponse"];
                    };
                };
                /** @description Invalid connect auth exchange request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect auth result is invalid */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect intent not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect intent expired */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect auth exchange unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connect/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Connect Session
         * @description Get SDK-visible SuperRare Connect session state.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Bearer Connect session ID returned by /v1/connect/auth/exchange. */
                    authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Connect session state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetConnectSessionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connect/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Connect Current User
         * @description Get limited user profile data visible to SuperRare Connect SDK consumers.
         */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Bearer Connect session ID returned by /v1/connect/auth/exchange. */
                    authorization?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current Connect user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetConnectCurrentUserResponse"];
                    };
                };
                /** @description No valid Connect session */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connect/checkout/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Connect Checkout Status
         * @description Get status for a SuperRare Connect checkout.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Connect checkout status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetConnectCheckoutStatusResponse"];
                    };
                };
                /** @description Connect checkout session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connect/intents/{intentId}/checkout/coinflow/buy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prepare Coinflow Card Checkout (Buy)
         * @description Create a Coinflow card-checkout session for a USDC Bazaar buy bound to the hosted-login wallet.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Intent-scoped execution token from the hosted Connect URL. */
                    "x-connect-execution-token"?: string;
                };
                path: {
                    intentId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PrepareCoinflowCardRequest"];
                };
            };
            responses: {
                /** @description Coinflow card checkout prepared */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PrepareCoinflowCheckoutResponse"];
                    };
                };
                /** @description Card checkout request is invalid or ineligible */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Hosted login session is not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect intent not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect intent expired */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Card checkout is not configured for this network */
                412: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Coinflow checkout failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/connect/intents/{intentId}/checkout/coinflow/mint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prepare Coinflow Card Checkout (Mint)
         * @description Create a Coinflow card-checkout session for a USDC release mint bound to the hosted-login wallet.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Intent-scoped execution token from the hosted Connect URL. */
                    "x-connect-execution-token"?: string;
                };
                path: {
                    intentId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PrepareCoinflowCardRequest"];
                };
            };
            responses: {
                /** @description Coinflow card checkout prepared */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PrepareCoinflowCheckoutResponse"];
                    };
                };
                /** @description Card checkout request is invalid or ineligible */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Hosted login session is not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect intent not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Connect intent expired */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Card checkout is not configured for this network */
                412: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
                /** @description Coinflow checkout failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConnectErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Nft: {
            /** @example 1-0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0-12345 */
            universalTokenId: string;
            /** @example 0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0 */
            contractAddress: string;
            /** @example 1 */
            chainId: string;
            /** @example 12345 */
            tokenId: string;
            /**
             * @example ERC721
             * @enum {string}
             */
            type: "ERC721" | "ERC1155";
            creator: components["schemas"]["User"];
            owner: components["schemas"]["User"];
            owners?: {
                /** @example 0xba5BDe662c17e2aDFF1075610382B9B691296350 */
                address: string;
                /** @example 1 */
                balance: string;
            }[];
            metadata: {
                /** @example Genesis */
                name: string | null;
                /** @example A unique digital artwork */
                description: string | null;
                /**
                 * @example [
                 *       "art",
                 *       "digital"
                 *     ]
                 */
                tags: string[];
                /** @example image/png */
                mediaType: string | null;
                /** @example https://example.com/image.png */
                imageUri: string | null;
                /** @example null */
                videoUri: string | null;
            };
            market: {
                listings: components["schemas"]["Listing"][];
                offers: components["schemas"]["Offer"][];
                auctions: components["schemas"]["Auction"][];
            };
            lastSale: components["schemas"]["LastSale"];
            attributes: {
                /** @example Background */
                property: string;
                /** @example Blue */
                value: string;
            }[];
            /** @example 1704067200 */
            createdAt: number;
        };
        User: {
            /** @example 0xba5BDe662c17e2aDFF1075610382B9B691296350 */
            address: string;
            /** @example satoshi */
            username: string | null;
            /** @example https://example.com/avatar.png */
            avatar: string | null;
            /** @example Satoshi Nakamoto */
            fullName: string | null;
        };
        Listing: {
            /** @example 0x1234567890abcdef1234567890abcdef12345678 */
            contractAddress: string;
            /**
             * @example SALE_PRICE
             * @enum {string}
             */
            type: "SALE_PRICE" | "BATCH_SALE_PRICE";
            price: components["schemas"]["CryptoValue"];
            /** @example 0xba5BDe662c17e2aDFF1075610382B9B691296350 */
            seller: string;
            /** @example 0xcf6398559ea0e93d7d7233ca93b09912da8ff57b45ebe7a3ede9c74d17a76f13 */
            merkleRoot?: string;
            allowlist?: {
                root: string;
            } | null;
        };
        CryptoValue: {
            /** @example 1000000000000000000 */
            cryptoAmount: string;
            currency: components["schemas"]["Currency"];
            /** @example 3500 */
            usdAmount: number | null;
        };
        Currency: {
            /** @example 0x0000000000000000000000000000000000000000 */
            address: string;
            /** @example ETH */
            symbol: string;
            /** @example 18 */
            decimals: number;
            /** @example 1 */
            chainId: number;
        };
        Offer: {
            /** @example 0x1234567890abcdef1234567890abcdef12345678 */
            contractAddress: string;
            /**
             * @example OFFER
             * @enum {string}
             */
            type: "OFFER" | "BATCH_OFFER";
            price: components["schemas"]["CryptoValue"];
            buyer: components["schemas"]["User"] & unknown;
            /** @example 0xba5BDe662c17e2aDFF1075610382B9B691296350 */
            buyerAddress: string;
        };
        Auction: {
            /** @example 0x1234567890abcdef1234567890abcdef12345678 */
            contractAddress: string;
            /**
             * @example RESERVE_AUCTION
             * @enum {string}
             */
            type: "RESERVE_AUCTION" | "BATCH_RESERVE_AUCTION" | "SCHEDULED_AUCTION";
            /**
             * @example RUNNING
             * @enum {string}
             */
            state: "PENDING" | "RUNNING" | "UNSETTLED";
            /** @example 2024-01-01T00:00:00.000Z */
            startTime: string | null;
            /** @example 2024-01-02T00:00:00.000Z */
            endTime: string | null;
            /** @example 0x0000000000000000000000000000000000000000 */
            currencyAddress: string;
            /** @example 0xba5BDe662c17e2aDFF1075610382B9B691296350 */
            sellerAddress: string;
            currentBid: components["schemas"]["CryptoValue"] & unknown;
            reservePrice: components["schemas"]["CryptoValue"] & unknown;
            highestBidder: components["schemas"]["User"] & unknown;
            /** @example 0xcf6398559ea0e93d7d7233ca93b09912da8ff57b45ebe7a3ede9c74d17a76f13 */
            merkleRoot?: string;
        };
        LastSale: {
            /** @example evt_123 */
            eventId: string;
            price: components["schemas"]["CryptoValue"];
        } | null;
        Pagination: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            perPage: number;
            /** @example 100 */
            totalCount: number;
            /** @example 5 */
            totalPages: number;
        };
        /**
         * @description Checksummed Ethereum address
         * @example 0xba5BDe662c17e2aDFF1075610382B9B691296350
         */
        EthereumAddress: string;
        /**
         * @description Supported blockchain network id
         * @example 1
         */
        ChainId: number;
        /**
         * @description Canonical NFT identifier in chainId-contractAddress-tokenId format.
         * @example 1-0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0-12345
         */
        UniversalTokenId: string;
        NftEvent: components["schemas"]["SaleEvent"] | components["schemas"]["TransferEvent"] | components["schemas"]["CreationEvent"] | components["schemas"]["ListingEvent"] | components["schemas"]["OfferEvent"] | components["schemas"]["AuctionBidEvent"] | components["schemas"]["AuctionLifecycleEvent"];
        SaleEvent: {
            /** @example evt_123 */
            eventId: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
            /** @example 0xabc123 */
            transactionHash: string | null;
            /** @example 12345678 */
            blockNumber: number | null;
            /** @enum {string} */
            eventType: "SETTLE_AUCTION" | "TAKE_LISTING" | "TAKE_OFFER";
            buyer: components["schemas"]["User"];
            seller: components["schemas"]["User"];
            price: components["schemas"]["CryptoValue"];
        };
        TransferEvent: {
            /** @example evt_123 */
            eventId: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
            /** @example 0xabc123 */
            transactionHash: string | null;
            /** @example 12345678 */
            blockNumber: number | null;
            /** @enum {string} */
            eventType: "TRANSFER_NFT" | "TRANSFER_NFT_SUPPLY";
            from: components["schemas"]["User"];
            to: components["schemas"]["User"];
            /** @example 1 */
            amount?: string;
        };
        CreationEvent: {
            /** @example evt_123 */
            eventId: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
            /** @example 0xabc123 */
            transactionHash: string | null;
            /** @example 12345678 */
            blockNumber: number | null;
            /** @enum {string} */
            eventType: "CREATE_NFT" | "CREATE_NFT_SUPPLY";
            creator: components["schemas"]["User"];
            /** @example 100 */
            amount?: string;
        };
        ListingEvent: {
            /** @example evt_123 */
            eventId: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
            /** @example 0xabc123 */
            transactionHash: string | null;
            /** @example 12345678 */
            blockNumber: number | null;
            /** @enum {string} */
            eventType: "MAKE_LISTING";
            price: components["schemas"]["CryptoValue"];
            targetBuyer: components["schemas"]["User"] & unknown;
        };
        OfferEvent: {
            /** @example evt_123 */
            eventId: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
            /** @example 0xabc123 */
            transactionHash: string | null;
            /** @example 12345678 */
            blockNumber: number | null;
            /** @enum {string} */
            eventType: "MAKE_OFFER" | "CANCEL_OFFER";
            buyer: components["schemas"]["User"];
            price: components["schemas"]["CryptoValue"];
        };
        AuctionBidEvent: {
            /** @example evt_123 */
            eventId: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
            /** @example 0xabc123 */
            transactionHash: string | null;
            /** @example 12345678 */
            blockNumber: number | null;
            /** @enum {string} */
            eventType: "MAKE_AUCTION_BID";
            bidder: components["schemas"]["User"];
            price: components["schemas"]["CryptoValue"];
            previousBidder: components["schemas"]["User"] & unknown;
            /** @example false */
            extendsAuction: boolean;
        };
        AuctionLifecycleEvent: {
            /** @example evt_123 */
            eventId: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
            /** @example 0xabc123 */
            transactionHash: string | null;
            /** @example 12345678 */
            blockNumber: number | null;
            /** @enum {string} */
            eventType: "CREATE_RESERVE_AUCTION" | "CREATE_SCHEDULED_AUCTION" | "START_AUCTION" | "END_AUCTION" | "CANCEL_AUCTION" | "CLOSE_AUCTION";
            seller: components["schemas"]["User"] & unknown;
            buyer: components["schemas"]["User"] & unknown;
            price: components["schemas"]["CryptoValue"] & unknown;
            minimumBid: components["schemas"]["CryptoValue"] & unknown;
            /** @example 2024-01-01T00:00:00.000Z */
            startTime: string | null;
        };
        CreateNftMetadataResponse: {
            cid: string;
            ipfsUrl: string;
            gatewayUrl: string;
            metadata: {
                name: string;
                description: string;
                image: string;
                media: {
                    uri: string;
                    mimeType: string;
                    size?: number;
                    dimensions?: string;
                };
                animation_url?: string;
                tags: string[];
                attributes?: {
                    trait_type: string;
                    value: string | number | boolean;
                    display_type?: string;
                }[];
            };
        };
        CreateNftMetadataRequest: {
            /** @example My NFT */
            name: string;
            /** @example A beautiful artwork */
            description: string;
            /**
             * @example [
             *       "art",
             *       "digital"
             *     ]
             */
            tags: string[];
            attributes?: {
                trait_type: string;
                value: string | number | boolean;
                display_type?: string;
            }[];
            nftMedia: components["schemas"]["NftMediaInput"];
        };
        NftMediaInput: {
            image: components["schemas"]["MediaAsset"];
            video?: components["schemas"]["MediaAsset"];
            threeD?: components["schemas"]["MediaAsset"];
            html?: components["schemas"]["MediaAsset"];
        };
        MediaAsset: {
            /**
             * Format: uri
             * @example ipfs://QmExample
             */
            url: string;
            /** @example image/png */
            mimeType: string;
            /** @example 1024000 */
            size: number;
            dimensions?: {
                width: number;
                height: number;
            };
        };
        CreateMediaUploadResponse: {
            /** @example abc123 */
            uploadId: string;
            /** @example a1b2c3d4/artwork.png */
            key: string;
            /** @example superrare-ipfs */
            bucket: string;
            /** @example 10000000 */
            partSize: number;
            presignedUrls: string[];
            /** @example https://superrare.myfilebase.com */
            gatewayBaseUrl: string;
        };
        CreateMediaUploadRequest: {
            /** @example 5000000 */
            fileSize: number;
            /** @example artwork.png */
            filename?: string;
        };
        IpfsUploadResponse: {
            /** @example QmExampleCid */
            cid: string;
            /** @example ipfs://QmExampleCid */
            ipfsUrl: string;
            /** @example https://superrare.myfilebase.com/ipfs/QmExampleCid */
            gatewayUrl: string;
        };
        CompleteMediaUploadRequest: {
            /** @example a1b2c3d4/artwork.png */
            key: string;
            /** @example abc123 */
            uploadId: string;
            /** @example superrare-ipfs */
            bucket: string;
            parts: {
                ETag: string;
                PartNumber: number;
            }[];
        };
        GenerateMediaResponse: {
            media: {
                uri: string;
                mimeType: string;
                size?: number;
                dimensions?: string;
            };
        };
        GenerateMediaRequest: {
            /** @example ipfs://QmMediaCid */
            uri: string;
            /** @example image/png */
            mimeType: string;
        };
        Collection: {
            /** @example col_123 */
            collectionId: string;
            /** @example SuperRare Genesis */
            name: string | null;
            /** @example The original SuperRare collection */
            description: string | null;
            /** @example SUPR */
            symbol: string | null;
            /** @example https://example.com/banner.png */
            bannerImage: string | null;
            /** @example https://example.com/preview.png */
            previewImage: string | null;
            owner: components["schemas"]["User"];
            stats: {
                /** @example 1000 */
                tokenCount: number;
                /** @example 250 */
                collectorCount: number;
                /** @example 500 */
                floorPriceUsd: number | null;
                /** @example 10000 */
                topOfferUsd: number | null;
                /** @example 5000000 */
                saleVolumeUsd: number | null;
            };
            /**
             * @example [
             *       "Background",
             *       "Eyes",
             *       "Mouth"
             *     ]
             */
            attributes: string[];
            /**
             * @example [
             *       1
             *     ]
             */
            chainIds: number[];
            /**
             * @description High-level collection category. Null if unknown.
             * @example CONTRACT
             * @enum {string|null}
             */
            collectionType: "CONTRACT" | "LAZY_MINT" | "ASYNC_BLUEPRINT" | "GENERAL" | "MULTI_CONTRACT" | null;
            /**
             * @description On-chain contract standard/protocol backing the collection. Use this to determine which minting API/path applies. Null if not a single-contract collection or unknown.
             * @example RARE_PROTOCOL_LAZY_SOVEREIGN_NFT
             * @enum {string|null}
             */
            nftContractType: "GENERIC_ERC_721_NFT_CONTRACT" | "GENERIC_ERC_1155_NFT_CONTRACT" | "OLD_ASYNC_BLUEPRINT" | "ASYNC_BLUEPRINT" | "RARE_PROTOCOL_SOVEREIGN_NFT" | "RARE_PROTOCOL_LAZY_SOVEREIGN_NFT" | "RARE_PROTOCOL_SOVEREIGN_BATCH_MINT" | "SUPERRARE_V_1" | "SUPERRARE_V_2" | "RARE_SPACE_NFT_CONTRACT" | "LIQUID_LENS_ERC_721_CONTRACT" | null;
            /** @example 1704067200 */
            createdAt: number;
        };
        ImportCollectionResponse: {
            imported: boolean;
            collection?: {
                name: string;
                symbol: string;
            };
        };
        ImportCollectionRequest: {
            chainId: components["schemas"]["ChainId"];
            contractAddress: components["schemas"]["EthereumAddress"];
            ownerAddress: components["schemas"]["EthereumAddress"];
        };
        UserProfile: {
            /** @example 0xba5BDe662c17e2aDFF1075610382B9B691296350 */
            address: string;
            /** @example satoshi */
            username: string;
            /** @example Satoshi Nakamoto */
            fullName: string | null;
            stats: {
                /** @example 42 */
                created: number;
                /** @example 15 */
                owned: number;
                /** @example 1000 */
                followerCount: number;
                /** @example true */
                isCollector: boolean;
                /** @example true */
                isCreator: boolean;
            };
        };
        TokenPriceResponse: {
            data: {
                symbol: string;
                priceUsd: number;
                decimals: number;
                chainId: number;
                address: string;
            };
        };
        /**
         * @description Token symbol (case-insensitive)
         * @example rare
         */
        TokenSymbol: string;
        GenerateNftMerkleRootResponse: {
            /** @example 0xcf6398559ea0e93d7d7233ca93b09912da8ff57b45ebe7a3ede9c74d17a76f13 */
            merkleRoot: string;
            /** @example 0xcf6398559ea0e93d7d7233ca93b09912da8ff57b45ebe7a3ede9c74d17a76f13.json */
            key: string;
        };
        GenerateNftMerkleRootRequest: {
            nfts: components["schemas"]["NftMerkleRootEntry"][];
        };
        NftMerkleRootEntry: {
            contractAddress: components["schemas"]["EthereumAddress"];
            /** @example 12345 */
            tokenId: string | number;
        };
        GenerateAddressMerkleRootResponse: {
            /** @example 0xcf6398559ea0e93d7d7233ca93b09912da8ff57b45ebe7a3ede9c74d17a76f13 */
            merkleRoot: string;
            locations: components["schemas"]["MerkleRootLocation"][];
        };
        MerkleRootLocation: {
            /** @enum {string} */
            storageTarget: "batch-listing" | "collection-allowlist";
            bucket: string;
            key: string;
            /** Format: uri */
            publicUrl: string;
        };
        GenerateAddressMerkleRootJsonRequest: {
            addresses: components["schemas"]["EthereumAddress"][];
            storageTarget?: components["schemas"]["MerkleRootStorageTarget"];
        };
        /**
         * @description Storage destination for address merkle roots
         * @default both
         * @example both
         * @enum {string}
         */
        MerkleRootStorageTarget: "batch-listing" | "collection-allowlist" | "both";
        GenerateAddressMerkleRootFormRequest: {
            /**
             * Format: binary
             * @description CSV file with an address column
             */
            file: string;
            storageTarget?: components["schemas"]["MerkleRootStorageTarget"];
        };
        GenerateNftMerkleProofResponse: {
            /** @example 0xcf6398559ea0e93d7d7233ca93b09912da8ff57b45ebe7a3ede9c74d17a76f13 */
            root: string;
            /** @example 0x8Db4B93Fa258E1c265d46f861ae9EbDE0B938670 */
            contractAddress: string;
            /** @example 12345 */
            tokenId: string;
            /** @example 0x83a68bd27e04afae4b40e8647019086ae8b4915bb243a4cf186f6271e1e65341 */
            leaf: string;
            proof: string[];
        };
        GenerateNftMerkleProofRequest: {
            /** @example 1 */
            chainId: number;
            contractAddress: components["schemas"]["EthereumAddress"];
            /** @example 12345 */
            tokenId: string | number;
            /** @example 0xcf6398559ea0e93d7d7233ca93b09912da8ff57b45ebe7a3ede9c74d17a76f13 */
            root?: string;
            context?: components["schemas"]["NftMerkleProofContext"];
            creator?: components["schemas"]["EthereumAddress"];
        };
        /**
         * @description Market state context used when resolving a root from Typesense
         * @example batch-listing
         * @enum {string}
         */
        NftMerkleProofContext: "batch-listing" | "batch-auction" | "batch-offer";
        GenerateAddressMerkleProofResponse: {
            /** @example 0xcf6398559ea0e93d7d7233ca93b09912da8ff57b45ebe7a3ede9c74d17a76f13 */
            root: string;
            /** @example 0x8Db4B93Fa258E1c265d46f861ae9EbDE0B938670 */
            address: string;
            /** @example 0x83a68bd27e04afae4b40e8647019086ae8b4915bb243a4cf186f6271e1e65341 */
            leaf: string;
            proof: string[];
        };
        GenerateAddressMerkleProofRequest: {
            /** @example 0xcf6398559ea0e93d7d7233ca93b09912da8ff57b45ebe7a3ede9c74d17a76f13 */
            root: string;
            address: components["schemas"]["EthereumAddress"];
            storageTarget?: components["schemas"]["MerkleRootProofStorageTarget"];
        };
        /**
         * @description Storage source for address merkle proof generation
         * @default collection-allowlist
         * @example collection-allowlist
         * @enum {string}
         */
        MerkleRootProofStorageTarget: "batch-listing" | "collection-allowlist";
        CreateConnectIntentResponse: {
            data: {
                /** @example connect_intent_placeholder */
                intentId: string;
                /** @example https://connect.superrare.com/action/connect_intent_placeholder */
                url: string;
                /** @example 2026-06-19T20:00:00.000Z */
                expiresAt: string;
            };
        };
        ConnectErrorResponse: {
            error: string;
        };
        CreateConnectIntentRequest: {
            action: components["schemas"]["ConnectActionInput"];
            /**
             * @description Optional SDK-reported window.location.origin. Must match the Origin header when provided.
             * @example https://artist.example
             */
            initiatingOrigin?: string;
            /**
             * @description Relative path on the initiating origin.
             * @example /checkout/complete
             */
            returnPath?: string;
            /** @example state_123 */
            state: string;
            payment?: components["schemas"]["ConnectIntentPayment"];
        };
        ConnectActionInput: {
            /** @enum {string} */
            type: "login";
        } | {
            /** @enum {string} */
            type: "buy";
            target: components["schemas"]["ConnectErc721DirectListingTarget"] | components["schemas"]["ConnectErc721BatchListingTarget"];
            expected: components["schemas"]["ConnectExpectedPriceTerms"];
        } | {
            /** @enum {string} */
            type: "buy";
            target: components["schemas"]["ConnectErc1155ListingTarget"];
            expected: components["schemas"]["ConnectExpectedUnitPriceTerms"];
        } | {
            /** @enum {string} */
            type: "bid";
            target: components["schemas"]["ConnectErc721ReserveAuctionTarget"] | components["schemas"]["ConnectErc721BatchReserveAuctionTarget"];
            bid: components["schemas"]["ConnectBidTerms"];
        } | {
            /** @enum {string} */
            type: "mint";
            target: components["schemas"]["ConnectErc721ReleaseTarget"] | components["schemas"]["ConnectErc1155ReleaseTarget"];
            purchase: components["schemas"]["ConnectPurchaseTerms"];
        } | {
            /** @enum {string} */
            type: "checkout";
            target: components["schemas"]["ConnectErc1155CheckoutTarget"];
        };
        ConnectErc721DirectListingTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "erc721-direct-listing";
            chainId: components["schemas"]["ChainId"];
            contract: components["schemas"]["EthereumAddress"];
            /** @example 123 */
            tokenId: string;
            target?: components["schemas"]["EthereumAddress"];
        };
        ConnectErc721BatchListingTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "erc721-batch-listing";
            chainId: components["schemas"]["ChainId"];
            creator: components["schemas"]["EthereumAddress"];
            /** @example 0xcf6398559ea0e93d7d7233ca93b09912da8ff57b45ebe7a3ede9c74d17a76f13 */
            root: string;
            contract: components["schemas"]["EthereumAddress"];
            /** @example 123 */
            tokenId: string;
        };
        ConnectExpectedPriceTerms: {
            /** @example ETH */
            currency: string;
            /** @example 1.2 */
            price: string;
        };
        ConnectErc1155ListingTarget: {
            /** @enum {string} */
            kind: "erc1155-listing";
            chainId: components["schemas"]["ChainId"];
            contract: components["schemas"]["EthereumAddress"];
            seller: components["schemas"]["EthereumAddress"];
            /** @example 123 */
            tokenId: string;
            /** @example 2 */
            quantity: string;
        };
        ConnectExpectedUnitPriceTerms: {
            /** @example ETH */
            currency: string;
            /** @example 1.2 */
            unitPrice: string;
        };
        ConnectErc721ReserveAuctionTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "erc721-reserve-auction";
            chainId: components["schemas"]["ChainId"];
            contract: components["schemas"]["EthereumAddress"];
            /** @example 123 */
            tokenId: string;
        };
        ConnectErc721BatchReserveAuctionTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "erc721-batch-reserve-auction";
            chainId: components["schemas"]["ChainId"];
            creator: components["schemas"]["EthereumAddress"];
            /** @example 0xcf6398559ea0e93d7d7233ca93b09912da8ff57b45ebe7a3ede9c74d17a76f13 */
            root: string;
            contract: components["schemas"]["EthereumAddress"];
            /** @example 123 */
            tokenId: string;
        };
        ConnectBidTerms: {
            /** @example ETH */
            currency: string;
            /** @example 1.2 */
            amount: string;
        };
        ConnectErc721ReleaseTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "erc721-release";
            chainId: components["schemas"]["ChainId"];
            contract: components["schemas"]["EthereumAddress"];
        };
        ConnectErc1155ReleaseTarget: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "erc1155-release";
            chainId: components["schemas"]["ChainId"];
            contract: components["schemas"]["EthereumAddress"];
            /** @example 123 */
            tokenId: string;
        };
        ConnectPurchaseTerms: {
            /** @example 2 */
            quantity: string;
            /** @example ETH */
            currency?: string;
            /** @example 1.2 */
            unitPrice?: string;
        };
        ConnectErc1155CheckoutTarget: {
            /** @enum {string} */
            kind: "erc1155-checkout";
            chainId: components["schemas"]["ChainId"];
            items: (components["schemas"]["ConnectErc1155CheckoutReleaseItem"] | components["schemas"]["ConnectErc1155CheckoutListingItem"])[];
        };
        ConnectErc1155CheckoutReleaseItem: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "release";
            contract: components["schemas"]["EthereumAddress"];
            /** @example 123 */
            tokenId: string;
            /** @example 2 */
            quantity: string;
            expected?: components["schemas"]["ConnectExpectedUnitPriceTerms"];
        };
        ConnectErc1155CheckoutListingItem: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "listing";
            contract: components["schemas"]["EthereumAddress"];
            seller: components["schemas"]["EthereumAddress"];
            /** @example 123 */
            tokenId: string;
            /** @example 2 */
            quantity: string;
            expected: components["schemas"]["ConnectExpectedUnitPriceTerms"];
        };
        ConnectIntentPayment: {
            /** @enum {string} */
            method?: "card";
            recipient?: components["schemas"]["EthereumAddress"];
            /** @example collector@example.com */
            email?: string;
        };
        GetConnectIntentResponse: {
            data: components["schemas"]["ConnectIntent"];
        };
        ConnectIntent: {
            /** @example connect_intent_placeholder */
            intentId: string;
            type: components["schemas"]["ConnectActionType"];
            status: components["schemas"]["ConnectIntentStatus"];
            /** @example https://artist.example */
            initiatingOrigin?: string;
            /** @example /checkout/complete */
            returnPath: string;
            /** @example 2026-06-19T20:00:00.000Z */
            expiresAt: string;
            resolvedActionSnapshot?: components["schemas"]["ConnectResolvedActionSnapshot"];
            result?: components["schemas"]["ConnectIntentResult"];
            error?: components["schemas"]["ConnectFlowError"];
            payment?: components["schemas"]["ConnectIntentPayment"];
        };
        /**
         * @example checkout
         * @enum {string}
         */
        ConnectActionType: "login" | "checkout" | "bid" | "buy" | "mint";
        /**
         * @example pending
         * @enum {string}
         */
        ConnectIntentStatus: "pending" | "requires_user" | "processing" | "completed" | "failed" | "cancelled" | "expired";
        ConnectResolvedActionSnapshot: {
            actionKey: string;
            /** @enum {string} */
            actionType: "checkout" | "bid" | "buy" | "mint";
            resolvedAt: string;
            targetKind: components["schemas"]["ConnectActionTargetKind"];
            terms: {
                amount?: string;
                available: boolean;
                currency?: string;
                marketplace?: string;
                /** @example 0xcf6398559ea0e93d7d7233ca93b09912da8ff57b45ebe7a3ede9c74d17a76f13 */
                merkleRoot?: string;
                merkleProof?: string[];
                price?: string;
                quantity?: string;
                quantityAvailable?: string;
                seller?: string;
                unitPrice?: string;
            };
        };
        /** @enum {string} */
        ConnectActionTargetKind: "erc721-direct-listing" | "erc721-batch-listing" | "erc1155-listing" | "erc721-reserve-auction" | "erc721-batch-reserve-auction" | "erc721-release" | "erc1155-release" | "erc1155-checkout";
        ConnectIntentResult: {
            /** @example 0x0000000000000000000000000000000000000000000000000000000000000000 */
            approvalTxHash?: string;
            /** @example connect_session_placeholder */
            sessionId?: string;
            /** @example 0x0000000000000000000000000000000000000000000000000000000000000000 */
            transactionHash?: string;
        };
        ConnectFlowError: {
            /** @example transaction_rejected */
            code: string;
            /** @example The wallet transaction was rejected. */
            message: string;
        };
        UpdateConnectIntentExecutionResponse: {
            data: components["schemas"]["ConnectIntent"];
        };
        UpdateConnectIntentExecutionRequest: {
            /** @enum {string} */
            status: "processing";
            /** @example 0x0000000000000000000000000000000000000000000000000000000000000000 */
            approvalTxHash?: string;
            /** @example 0x0000000000000000000000000000000000000000000000000000000000000000 */
            transactionHash?: string;
        } | {
            /** @enum {string} */
            status: "completed";
            /** @example 0x0000000000000000000000000000000000000000000000000000000000000000 */
            approvalTxHash?: string;
            /** @example 0x0000000000000000000000000000000000000000000000000000000000000000 */
            transactionHash: string;
        } | {
            /** @enum {string} */
            status: "failed";
            /** @example 0x0000000000000000000000000000000000000000000000000000000000000000 */
            approvalTxHash?: string;
            error: components["schemas"]["ConnectFlowError"];
            /** @example 0x0000000000000000000000000000000000000000000000000000000000000000 */
            transactionHash?: string;
        } | {
            /** @enum {string} */
            status: "cancelled";
            error?: components["schemas"]["ConnectFlowError"];
        };
        ExchangeConnectIntentExecutionSessionResponse: {
            data: {
                /** @example connect_execution_placeholder */
                executionToken: string;
            };
        };
        ExchangeConnectIntentExecutionSessionRequest: {
            /** @example connect_execution_session_placeholder */
            executionSessionId: string;
        };
        CompleteHostedConnectAuthResponse: {
            data: {
                /** @example connect_auth_code_placeholder */
                code: string;
                /** @example connect_intent_placeholder */
                intentId: string;
                /** @example state_123 */
                state: string;
                /**
                 * Format: uri
                 * @example https://artist.example/account?intentId=connect_intent_placeholder&state=state_123&code=connect_auth_code_placeholder
                 */
                returnTarget: string;
                /** @example 2026-06-19T20:00:00.000Z */
                expiresAt: string;
            };
        };
        CompleteHostedConnectAuthRequest: {
            /** @example connect_intent_placeholder */
            intentId: string;
        };
        ExchangeConnectAuthResponse: {
            data: {
                session: components["schemas"]["ConnectSession"];
            };
        };
        ConnectSession: {
            /** @example connect_session_placeholder */
            sessionId: string;
            /** @example user_placeholder */
            userId: string;
            /** @example 0x0000000000000000000000000000000000000000 */
            address: string;
            /** @example 2026-06-19T20:00:00.000Z */
            expiresAt: string;
        };
        ExchangeConnectAuthRequest: {
            /** @example connect_auth_code_placeholder */
            code: string;
            /** @example connect_intent_placeholder */
            intentId: string;
            /** @example state_123 */
            state: string;
        };
        GetConnectSessionResponse: {
            data: {
                /** @example true */
                authenticated: boolean;
                session?: components["schemas"]["ConnectSession"];
            };
        };
        GetConnectCurrentUserResponse: {
            data: {
                /** @example 0x0000000000000000000000000000000000000000 */
                address: string;
                /** @example superrare-user */
                username: string | null;
                /** @example SuperRare User */
                fullName: string | null;
                /** @example https://example.com/avatar.png */
                avatarUri: string | null;
            };
        };
        GetConnectCheckoutStatusResponse: {
            data: {
                /** @example connect_session_placeholder */
                sessionId: string;
                status: components["schemas"]["ConnectCheckoutStatus"];
                /** @example https://artist.example */
                initiatingOrigin?: string;
                /** @example /checkout/complete */
                returnPath?: string;
                /** @example connect_intent_placeholder */
                intentId?: string;
                /** @example 2026-06-19T20:00:00.000Z */
                expiresAt?: string;
                resolvedActionSnapshot?: components["schemas"]["ConnectResolvedActionSnapshot"];
                /** @example 0x0000000000000000000000000000000000000000000000000000000000000000 */
                approvalTxHash?: string;
                /** @example 0x0000000000000000000000000000000000000000000000000000000000000000 */
                transactionHash?: string;
                error?: components["schemas"]["ConnectFlowError"];
            };
        };
        /**
         * @example pending
         * @enum {string}
         */
        ConnectCheckoutStatus: "pending" | "processing" | "completed" | "failed" | "cancelled" | "expired";
        PrepareCoinflowCheckoutResponse: {
            data: {
                checkoutJwtToken: string;
                sessionKey: string;
                merchantId: string;
                /** @enum {string} */
                env: "prod" | "sandbox";
            };
        };
        PrepareCoinflowCardRequest: {
            buyerAddress: components["schemas"]["EthereumAddress"];
            /** @example collector@example.com */
            email?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
